name: Start Actions on Commit for Documentation
on:
  push:
      branches:
        - '**'
  
jobs:          
  documentation:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
         python-version: '3.10'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Start ollama server
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Run Llama 3
        run: ollama run llama3

      - name: Run documentation script
        run: cd repo_documentation && python app.py

      - name: Upload documentation output
        uses: actions/upload-artifact@v2
        with:
          name: validation-output
          path: repo_documentation/docs_output/
