name: Start Actions on Commit
on:
  push:
      branches:
        - '**'
  pull_request:
      branches:
        - main

jobs:          
  documentation_and_validation:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Run documentation script
        run: ./repo_documentation/app.py

      - name: Run validation script
        run: ./repo_validation/app.py


  test_cases:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: windows-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run test cases in main 
        run: cd repo-client && pytest
