name: Start Actions on Commit
on:
  push:
      branches:
        - '**'
  pull_request:
      branches:
        - main

jobs:          
  documentation_and_validation:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
         python-version: '3.10'

      #- name: Install dependencies - will add once all dependencies are included

      - name: Run documentation script
        run: cd repo_documentation && python app.py

      - name: Run validation script
        run: cd repo_validation && python app.py


  test_cases:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: windows-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

     # - name: Install Dependencies - will add once all dependencies are included

      - name: Run test cases in main 
        run: cd repo_client && pytest
