name: Start Actions on Commit for Validation
on:
  push:
    branches:
      - '**'

jobs:
  documentation:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:  pip3 install -r requirements.txt

      - name: Start ollama server
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Run Llama 3
        run: ollama run llama3

      - name: Create docs_output directory
        run: mkdir -p repo_validation/docs_output

      - name: Set permissions for docs_output directory
        run: chmod 777 repo_validation/docs_output

      - name: Run validation script
        run: cd repo_validation && python app.py

      - name: Upload validation output
        uses: actions/upload-artifact@v2
        with:
          name: validation-output
          path: repo_validation/docs_output/
      
